# PostgreSQL. Versions 9.1 and up are supported.
#

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: kr_force_development
  username: <%= ENV['DB_USERNAME'] || Rails.application.credentials[Rails.env.to_sym][:db][:username] %>
  password: <%= ENV['DB_PASSWORD'] || Rails.application.credentials[Rails.env.to_sym][:db][:password] %>
  host: localhost

test:
  <<: *default
  database: kr_force_test
  username: <%= ENV['DB_USERNAME'] || Rails.application.credentials[Rails.env.to_sym][:db][:username] %>
  password: <%= ENV['DB_PASSWORD'] || Rails.application.credentials[Rails.env.to_sym][:db][:password] %>
  host: <%= ENV['DB_HOST'] || Rails.application.credentials[Rails.env.to_sym][:db][:host] %>
  port: <%= ENV['DB_PORT'] || Rails.application.credentials[Rails.env.to_sym][:db][:port] %>

staging:
  <<: *default
  database: kr_force_staging
  username: <%= Rails.application.credentials[Rails.env.to_sym][:db][:username] %>
  password: <%= Rails.application.credentials[Rails.env.to_sym][:db][:password] %>

production:
  <<: *default
  database: kr_force_production
  username: <%= Rails.application.credentials[Rails.env.to_sym][:db][:username] %>
  password: <%= Rails.application.credentials[Rails.env.to_sym][:db][:password] %>
